// src/app/
export const ACKNOWLEDGE_ERROR = 'ACKNOWLEDGE_ERROR';
export const ADD_ERROR = 'ADD_ERROR';
export const APP_INITIALIZED = 'APP_INITIALIZED';
export const CLEAR_ACTION_QUEUE = 'CLEAR_ACTION_QUEUE';
export const QUEUE_ACTION = 'QUEUE_ACTION';
export const RELOAD_APP = 'RELOAD_APP';
export const UPDATE_LOADING_COUNTER = 'UPDATE_LOADING_COUNTER';

// csv data file actions
export const FETCH_QUERY_HIVE_DATA='FETCH_QUERY_HIVE_DATA';
export const FETCH_QUERY_HIVE_DATA_RECEIVED='FETCH_QUERY_HIVE_DATA_RECEIVED';
export const FETCH_SAMPLE_H3_DATA='FETCH_SAMPLE_H3_DATA';
export const FETCH_SAMPLE_H3_DATA_RECEIVED='FETCH_SAMPLE_H3_DATA_RECEIVED';