// src/app/
export const ACKNOWLEDGE_ERROR = "ACKNOWLEDGE_ERROR";
export const ADD_ERROR = "ADD_ERROR";
export const APP_INITIALIZED = "APP_INITIALIZED";
export const CLEAR_ACTION_QUEUE = "CLEAR_ACTION_QUEUE";
export const QUEUE_ACTION = "QUEUE_ACTION";
export const RELOAD_APP = "RELOAD_APP";
export const UPDATE_LOADING_COUNTER = "UPDATE_LOADING_COUNTER";

export const FETCH_QUERY_HIVE_DATA = "FETCH_QUERY_HIVE_DATA";
export const FETCH_QUERY_HIVE_DATA_RECEIVED = "FETCH_QUERY_HIVE_DATA_RECEIVED";

export const FIRST_FETCH_H3HEX_LAYER_DATA = "FIRST_FETCH_H3HEX_LAYER_DATA";
export const FIRST_FETCH_H3HEX_LAYER_DATA_RECEIVED =
  "FIRST_FETCH_H3HEX_LAYER_DATA_RECEIVED";

export const SECOND_FETCH_H3HEX_LAYER_DATA = "SECOND_FETCH_H3HEX_LAYER_DATA";
export const SECOND_FETCH_H3HEX_LAYER_DATA_RECEIVED =
  "SECOND_FETCH_H3HEX_LAYER_DATA_RECEIVED";

export const THIRD_FETCH_H3HEX_LAYER_DATA = "THIRD_FETCH_H3HEX_LAYER_DATA";
export const THIRD_FETCH_H3HEX_LAYER_DATA_RECEIVED =
  "THIRD_FETCH_H3HEX_LAYER_DATA_RECEIVED";

export const COMBINE_H3HEX_LAYER_DATA = "COMBINE_H3HEX_LAYER_DATA";

export const FETCH_H3HEX_TO_ARC_LAYER_DATA = "FETCH_H3HEX_TO_ARC_LAYER_DATA";
export const FETCH_H3HEX_TO_ARC_LAYER_DATA_RECEIVED =
  "FETCH_H3HEX_TO_ARC_LAYER_DATA_RECEIVED";

export const FETCH_PREDICTION_LAYER_DATA = "FETCH_PREDICTION_LAYER_DATA";
export const FETCH_PREDICTION_LAYER_DATA_RECEIVED =
  "FETCH_PREDICTION_LAYER_DATA_RECEIVED";

export const FETCH_GEO_JSON_LAYER_DATA = "FETCH_GEO_JSON_LAYER_DATA";
export const FETCH_GEO_JSON_LAYER_DATA_RECEIVED =
  "FETCH_GEO_JSON_LAYER_DATA_RECEIVED";

export const UPDATE_SELECTED_COLOR = "UPDATE_SELECTED_COLOR";
export const UPDATE_PREDICTION_LAYER_SELECTED_COLOR =
  "UPDATE_PREDICTION_LAYER_SELECTED_COLOR";

//
export const RESET_PREDICTION_LAYER_VIEW = "RESET_PREDICTION_LAYER_VIEW";
export const RESET_ORIGIN_DESTINATION_VIEW = "RESET_ORIGIN_DESTINATION_VIEW";
